{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "ai-eval-platform.fullname" .) }}
  labels:
    {{- include "ai-eval-platform.labels" . | nindent 4 }}
    {{- include "ai-eval-platform.selectorLabels" . | nindent 4 }}
{{- end }}